version: 0.2

env:
  variables:
    AST_BASE_URL: "https://eu.ast.checkmarx.net/"
    AST_BASE_AUTH_URL: "https://eu.iam.checkmarx.net/"
    AST_AGENT: "AWSCodeBuild"
    AST_PROJECT_NAME: "JVL Demo"
    AST_PRESET: "Checkmarx Default"
    AST_SCANTYPE: "sast,sca,kics"
  parameter-store:
    AST_APIKEY: "/AST/APIKEY"
    AST_TENANT: "/AST/TENANT"
phases: 
  install: 
    runtime-versions: 
      java: corretto11
    commands:
      - echo Download CxAST CLI
      - CLI_VERSION=`wget -q "https://api.github.com/repos/Checkmarx/ast-cli/releases/latest" -O - | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
      - wget -O ~/ast-cli.tar.gz "https://github.com/Checkmarx/ast-cli/releases/download/${CLI_VERSION}/ast-cli_${CLI_VERSION}_linux_x64.tar.gz"
      - tar -xzvf ~/ast-cli.tar.gz -C ~
      - rm -rf ~/ast-cli.tar.gz
      - chmod +x ~/cx
  pre_build:
    commands:
      - echo No pre-build stage
  build:
    commands:
      - echo Building JavaVulnerableLab Project 
      - cd $CODEBUILD_SRC_DIR
      - mvn install -Dmaven.compiler.source=1.6 -Dmaven.compiler.target=1.6
  post_build: 
    commands: 
      - ~/cx scan create --agent "$AST_AGENT" --apikey "$AST_APIKEY" --base-auth-uri "$AST_BASE_AUTH_URL" --base-uri "$AST_BASE_URL" --tenant "$AST_TENANT" --project-name "$AST_PROJECT_NAME" --sast-preset-name "$AST_PRESET" --scan-types "$AST_SCANTYPE" --file-source "$CODEBUILD_SRC_DIR" --branch "$CODEBUILD_SOURCE_VERSION"